### ISSUE TITLE
Tutorial 5: Storing and retrieving All Todos

### ISSUE THREAD

**Issue by Ujjawal-K-Panchal** [IsaiahT-Tech/fastapi-series#2]
When I code the `create_todo()` like as shown in the program as:
```
@app.post('/todo/')
async def create_todo(todo: Todo):
	store_todo.append(todo)
	return todo
```
and then I call:
```
@app.get('/todo/', response_model = List[Todo])
async def get_all_todos():
	return store_todo
```
That doesn't work.

Hence, I changed the `create_todo()` as follows:
```
@app.post('/todo/')
async def create_todo(todo: Todo):
	store_todo.append(todo.dict())
	return todo
```
Then calling the `get_all_todos()`is worked for me.

**Comment by IsaiahT-Tech** [comment]
Thank you for your suggestion. I tested out the code, and both methods work fine.

**Comment by Ujjawal-K-Panchal** [comment]
I see... strange that first method didnot work for me. I'm using Windows 10. I'll close the issue in that case. Thanks for the quick response!
