### ISSUE TITLE
Code for tutorial 10

### ISSUE THREAD

**Issue by SnkSynthesis** [IsaiahT-Tech/fastapi-series#5]
The code for [tutorial 10](https://youtu.be/J7wh5iCydDI) seems to be missing.

**Comment by IsaiahT-Tech** [comment]
I did not notice that. Thank you, I will commit and push those changes into the repository.

**Comment by IsaiahT-Tech** [comment]
@all-contributors please add @SnkSynthesis  for helping with the fastapi-series

**Comment by IsaiahT-Tech** [comment]
@all-contributors please add @SnkSynthesis for fixing and helping with the fastapi-series

**Comment by IsaiahT-Tech** [comment]
@all-contributors please add @SnkSynthesis for fixing and helping with the tutorial fastapi-series

**Comment by IsaiahT-Tech** [comment]
Closed.
